name: Build and publish Docker image to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: cnpg-pgvector-vectorchord
  REGISTRY: ghcr.io
  TAG: 16-migration

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.TAG }}
          build-args: |
            CNPG_TAG=16
            PGVECTORS_TAG=v0.2.1
            TARGETARCH=amd64
